# Generated by Django 5.2.17 on 2026-08-26 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_projecthotkeypreference"),
        ("valtaris_sso", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValtarisProjectConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_slug", models.CharField(db_index=True, max_length=128)),
                ("min_tier", models.CharField(default="T1_associate", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valtaris_config",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
